data_extraction:
  time_trunc : day
  category : demanda
  subcategory : evolucion
  first_date : 2014-01-01
  max_time_call : 365
  output_path : data
  output_filename_data : raw.RData
  output_filename_date : last_date.RData