# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: update_data

on:
  schedule:
    - cron: '0 7 * * *' # Execute every day at 7
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install necesary libraries
        run: sudo apt-get install -y curl libssl-dev libcurl4-openssl-dev libxml2-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2 # Install R
        with: 
          r-version: '4.1.1'

      - name: Run Data Extraction
        run: Rscript src/data_extraction.R
      
      - name: git setting
        run: |
         git config --local user.email "tishijima@eco-pork.com"
         git config --local user.name "IshiTatsu-ep"
      
      - name: Push data to Github
        run: bash src/Pushdata.sh